---
  01_monitoring_url:
    description: "Engine API address"
    type: "string"
    required: true
    default: "https://engine1.localdomain/ovirt-engine/api"
    secret: false
  02_monitoring_username:
    description: "Engine account username"
    type: "string"
    default: "admin@ovirt@internal"
    required: true
  03_monitoring_password:
    description: "Engine account password"
    type: "string"
    default: "123qweASD@"
    secret: true
    required: true
  sys_controller_address:
    description: "XRM Controller connection address"
    type: "string"
    default: "http://st2:459Qdr_@xrm-controller:8080/ovirt"
    required: false
    secret: false
